# Generated by Django 5.2.5 on 2025-09-05 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_note_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-publish_date', 'topic_number']},
        ),
        migrations.AddField(
            model_name='note',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='note',
            name='topic_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
