# Generated by Django 5.2.5 on 2025-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
